apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nextcloud.fullname" . }}-mariadb-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
{{- with .Values.mariadbSecrets }}
  MYSQL_USER: {{ .MYSQL_USER | quote }}
  MYSQL_ROOT_PASSWORD: {{ .MYSQL_ROOT_PASSWORD | quote }}
  MYSQL_DATABASE: {{ .MYSQL_DATABASE | quote }}
  MYSQL_PASSWORD: {{ .MYSQL_PASSWORD | quote }}
{{- end }}
