apiVersion: v1
kind: Service
metadata:
  name: {{ include "nextcloud.fullname" . }}-mariadb
  namespace: {{ .Values.namespace }}
  labels:
    app: mariadb
spec:
  type: {{ .Values.service.mariadb.type }}
  ports:
    - port: {{ .Values.service.mariadb.port }}
      targetPort: {{ .Values.service.mariadb.targetPort }}
  selector:
    app: mariadb
