apiVersion: v1
kind: Service
metadata:
  name: {{ include "nextcloud.fullname" . }}-nextcloud
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.nextcloud.type }}
  selector:
    app: nextcloud
  ports:
  - name: http
    targetPort: {{ .Values.service.nextcloud.targetPort }}
    port: {{ .Values.service.nextcloud.port }}
