apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mariadb-db
  namespace: {{ .Values.namespace }}
spec:
  accessModes: {{ toYaml .Values.storage.accessModes | nindent 2 }}
  storageClassName: {{ .Values.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
