apiVersion: v1
kind: Service
metadata:
  name: {{ include "nextcloud.fullname" . }}-redis
  namespace: {{ .Values.namespace }}
  labels:
    app: redis
spec:
  type: {{ .Values.service.redis.type }}
  ports:
    - port: {{ .Values.service.redis.port }}
      targetPort: {{ .Values.service.redis.targetPort }}
  selector:
    app: redis
