apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vaultwarden.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "vaultwarden.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vaultwarden.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: vaultwarden
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: DOMAIN
              value: {{ .Values.domain | quote }}
            - name: SIGNUPS_ALLOWED
              value: "true"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: vw-data
              mountPath: /data
      volumes:
        - name: vw-data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "vaultwarden.fullname" .) }}