apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vaultwarden.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "vaultwarden.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vaultwarden.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: vaultwarden
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: DOMAIN
              value: {{ .Values.domain | quote }}
            # Pointing Vaultwarden to the mounted secret paths
            - name: ROCKET_TLS
              value: '{certs="/ssl/tls.crt",key="/ssl/tls.key"}'
          ports:
            - containerPort: 80
          volumeMounts:
            - name: vw-data
              mountPath: /data
            - name: ssl-certs
              mountPath: /ssl
              readOnly: true
      volumes:
        - name: vw-data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "vaultwarden.fullname" .) }}
        - name: ssl-certs
          secret:
            secretName: {{ .Values.sslSecretName }}