apiVersion: v1
kind: Secret
metadata:
  name: immich-db-secret
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.postgres.env.POSTGRES_PASSWORD | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.env.POSTGRES_PASSWORD | quote }}