apiVersion: v1
kind: Service
metadata:
  name: immich-server
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.port }}
      name: http
  selector:
    app: immich-server
