---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgres-shared.fullname" . }}-data
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
  {{- else }}
  storageClassName: ""
  {{- end }}
