apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres-shared.fullname" . }}
  labels:
    {{- include "postgres-shared.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.postgresPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: {{ include "postgres-shared.fullname" . }}
