apiVersion: v2
name: nextcloud
description: Nextcloud with MariaDB, Redis, cert-manager PKCS12 keystore support
type: application
version: 0.1.1
appVersion: "1.0"
icon: https://www.nextcloud.com/wp-content/themes/nextcloudorg/assets/img/logo/nextcloud-logo-512.png
