{{- if and .Values.ingress.enabled .Values.ingress.tls.enabled .Values.ingress.tls.createCertificate }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.ingress.tls.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Values.ingress.tls.secretName }}
  commonName: {{ (index .Values.ingress.hosts 0).host }}
  dnsNames:
    {{- range .Values.ingress.hosts }}
    - {{ .host }}
    {{- end }}
  issuerRef:
    name: {{ .Values.ingress.tls.issuerRef.name }}
    kind: {{ .Values.ingress.tls.issuerRef.kind }}
{{- end }}
